<?php

  require_once (dirname(__FILE__).'/../../helpers/ViewHelper.php');
  $objHelper = new ViewHelper();

?>

  <div class="listwrapper">
    <table class="tablelist">
      <thead>
        <tr>
          <th class="topcornerleft"></th>
          <th class="topcheckbox"><input id="listSelectAll" type="checkbox" name="listSelectAll" /></th>
          <th class="topicon"></th>
          <th class="toptitle"><?php echo $this->translate->_('title'); ?></th>
          <th class="topauthor"><?php echo $this->translate->_('Author'); ?></th>
          <th class="topcreated"><?php echo $this->translate->_('uploaded'); ?></th>
          <th class="topcornerright"></th>
        </tr>
      </thead>
      <tbody>
        <?php echo $objHelper->getListView($this->objFiles); ?>
      </tbody>
    </table>
    <div class="listfooter">
      <div class="listfootercornerleft"></div>
      <div class="listfootercornerright"></div>
      <div class="listfootercontent">
        <div class="listpagination">
          <!--<div class="listback">
            <div class="listfooterbutton">
              <div class="buttonleft"></div>
              <div class="buttoncenter">zur&uuml;ck</div>
              <div class="buttonright"></div>
              <div class="clear"></div>
            </div>
          </div>
          <div class="listjumptopage">Seite:
            <select name="page">
              <option value="1">1</option>
              <option value="1">2</option>
              <option value="1">3</option>
              <option value="1">4</option>
              <option value="1">5</option>
            </select>
          </div>
          <div class="listnext">            
            <div class="listfooterbutton">
              <div class="buttonleft"></div>
              <div class="buttoncenter">weiter</div>
              <div class="buttonright"></div>
              <div class="clear"></div>
            </div>
          </div> -->
          <div class="clear"></div>
        </div>
        <!--<div class="listentriespage">Eintr&auml;ge pro Seite:
	        <select name="showentries">
	          <option value="20">20</option>
	          <option value="50">50</option>
	          <option value="70">70</option>
	          <option value="100">100</option>
	        </select>
	      </div> -->
	      <div class="clear"></div>	      
      </div>
    </div>
    <div class="spacer2"></div>
    <div class="clear"></div>
  </div> 