<?php
  require_once (dirname(__FILE__).'/../../helpers/PageHelper.php');
  $objHelper = new PageHelper();
?>
                 <div class="formsubtitle"><?php echo $this->translate->_('Recent_changes'); ?></div>
                 <table class="tablelist">
                   <thead>
                     <tr>
                       <th class="topcornerleft"></th>
                       <th class="topcheckbox"></th>
                       <th class="toptitle"><?php echo $this->translate->_('title'); ?></th>
                       <th class="topauthor"><?php echo $this->translate->_('Modified_by'); ?></th>
                       <th class="topchanged"><?php echo $this->translate->_('changed'); ?></th>
                       <th class="topcreated"><?php echo $this->translate->_('created'); ?></th>
                       <th class="topcornerright"></th>
                     </tr>
                   </thead>
                   <tbody>
	                   <?php echo $objHelper->getDashboardListOutput($this->objPages);?>
                   </tbody>
                 </table>
                 <div class="listfooter">
						       <div class="listfootercornerleft"></div>
						       <div class="listfootercornerright"></div>
						     </div>
						     <div class="spacer2"></div>