<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
  <head>
    <title>ZOOLU - MEDIEN</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Language" content="de" />
    <meta name="language" content="de" />

    <!-- ext.js css -->
    <link rel="stylesheet" type="text/css" href="/zoolu/js_incs/ext.js/resources/css/ext-all.css?v=<?php echo $this->cssVersion; ?>" />
    <link rel="stylesheet" type="text/css" href="/zoolu/js_incs/ext.js/resources/css/xtheme-gray.css?v=<?php echo $this->cssVersion; ?>" />

    <!-- css -->
    <link href="/zoolu/css/core_main.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />
    <link href="/zoolu/css/core_navigation.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />
    <link href="/zoolu/css/core_content.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />
    <link href="/zoolu/css/core_font.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />    
    <link href="/zoolu/css/media.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />

    <!-- libaries -->
    <script type="text/javascript" src="/zoolu/js_incs/prototype/prototype.js?v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/js_incs/script.aculous/scriptaculous.js?v=<?php echo $this->jsVersion; ?>"></script>
       
  </head>
  <body id="myBody">

    <!-- navigation top -->
    <div id="navigation-top">
      
      <div id="top">
        
        <div class="toplogo">
          <a href="/zoolu">
            <img src="/zoolu/images/main/logo_zoolu_small.png" width="69" height="17" alt="ZOOLU"/>
          </a>
        </div>
        <div class="topright">
          <div class="faqtitle"><a href="#"><?php echo $this->translate->_('Report_bugs'); ?></a> | <a href="#"><?php echo $this->translate->_('Help_and_FAQ'); ?></a></div>
          <div class="faqicon"><img src="/zoolu/images/icons/icon_help.png" width="16" height="16"/></div>
          <div class="clear"></div>
        </div>
        
        <div class="clear"></div>        
      </div>  <!-- END top -->
      
      <?php echo $this->layout()->userinfo; ?>
      
      <!-- 
      <div id="navtopleft">
        <img id="navtopleftimg" width="5" height="40" src="/zoolu/images/main/bg_navigation_left.png"/>
      </div>
       -->
       
      <div id="navtopleftclient">
        <img id="navtopleftimgclient" width="42" height="40" src="/zoolu/images/zoolu_client_logo.png"/>
      </div>
      
      <div id="navtopwrapper">
        <div id="navtopinner">
          <div class="navtop">
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_left.png"/></div>
            <div class="navtoplink" onmouseover="this.style.cursor='pointer';" onclick="location.href='/zoolu/cms'"><?php echo strtoupper($this->translate->_('Portals')); ?></div>
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_right.png"/></div>
          </div>
          <div class="navtop">
            <div class="navtopcorner_on"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_left.png"/></div>
            <div class="navtoplink_on" onmouseover="this.style.cursor='pointer';" onclick="location.href='/zoolu/media'"><?php echo strtoupper($this->translate->_('Media')); ?></div>
            <div class="navtopcorner_on"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_right.png"/></div>
          </div>
          <div class="navtopinnerright">
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_left.png"/></div>
            <div class="navtoplink" onmouseover="this.style.cursor='pointer';" onclick="location.href='/zoolu/properties'"><?php echo $this->translate->_('Settings'); ?></div>
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_right.png"/></div>
          </div>
          <div class="navtopinnerright">
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_left.png"/></div>
            <div class="navtoplink" onmouseover="this.style.cursor='pointer';" onclick="location.href='/zoolu/users'"><?php echo $this->translate->_('User_administration'); ?></div>
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_right.png"/></div>
          </div>
          <div class="clear"></div>
        </div>
        <div id="navtopbreadcrumb" style="display:none;"></div>
      </div>
      
      <div id="navtopright">
        <img id="navtoprightimg" width="5" height="40" src="/zoolu/images/main/bg_navigation_right.png"/>
      </div>

    </div> 
    <!-- END navigation top -->

    <?php echo $this->layout()->navigation; ?>

    <!-- content -->
    <div id="content">
      <div id="divFormContainer" >
         
        <!-- content edit -->
        <div id="genFormContainer" class="contentedit" style="display:none;">
        </div>
          
        <!-- content function widget -->
        <div id="genFormSaveContainer" class="contentfunction" style="display:none;">

          <!-- widget: save, delete, infos, ... -->
          <div class="widgetfunctions">
            <div class="widget224content">
              <div class="widgetcontenttop">               
                
                <!-- alerts for saving, editing, deleting, ... -->
                <div id="divFormSaveLoader" class="alertsave" style="display:none;">
                  <div class="alertsaveloader white"><img src="/zoolu/images/main/loader_save.gif" />Abbrechen</div>
                </div>                
                <div id="divFormSaveSucces" class="alertsavesucces" style="display:none;">Gespeichert!</div>
                <div id="divFormSaveError" class="alertsaveerror" style="display:none;">Speichern nicht möglich!</div>
                <div id="divFormDeleteSucces" class="alertdeletesucces" style="display:none;">Gel&ouml;scht!</div>
                
                <!-- save button -->
                <div id="buttonsave" onclick="myForm.save();">
                  <div class="button25leftOn"></div>
                  <div class="button25centerOn">
                    <img class="iconsave" src="/zoolu/images/icons/icon_save_black.png" width="13" height="13"/>
                    <div>Speichern</div>
                  </div>
                  <div class="button25rightOn"></div>
                  <div class="clear"></div>
                </div>

                <!-- delete button -->
                <div id="buttondelete" onclick="myForm.deleteElement();" style="display:none;">
                  <div class="button25leftOff"></div>
                  <div class="button25centerOff">
                    <img class="icondelete" src="/zoolu/images/icons/icon_delete_white.png" width="11" height="14"/>
                    <div>L&ouml;schen</div>
                  </div>
                  <div class="button25rightOff"></div>
                  <div class="clear"></div>
                </div>

                <div class="clear"></div>
              </div>

              <div class="widgetcontentmain" id="divWidgetMetaInfos">                
              </div>
              
            </div>
          </div>
        </div>
      </div> <!-- END divFormContainer -->
      
      <div id="divMediaContainer" style="display:none;">
              
        <!-- media head -->
        <div class="contenthead">
          
          <div id="mediabuttons">
            <div class="buttonsdivider"></div>
            <!-- new button -->
            <div id="buttonmedianew" onclick="myMedia.getUploadWidget(); return false;">
              <div class="button25leftOn"></div>
              <div class="button25centerOn">
                <img class="iconsave" src="/zoolu/images/icons/icon_save_black.png" width="13" height="13"/>
                <div>Neu</div>
              </div>
              <div class="button25rightOn"></div>
              <div class="clear"></div>
            </div>
            <!-- edit menu -->          
            <div id="buttonmediaedit" onclick="return false;">
              <div class="buttonedittop"></div>
              <div id="buttonmediaedittitle" class="buttoneditmiddle white" onclick="myMedia.toggleMediaEditMenu(this.id); return false;">Bearbeiten</div>
              <div class="buttoneditbottom"></div>
              <div class="clear"></div>
            </div>            
            <div class="clear"></div>
            <div id="divMediaEditMenu" class="mediaeditmenu" style="display:none;">
              <div class="mediaeditmenuinner">
                <div class="mediaeditlink" onclick="myMedia.getFilesEditForm(); return false;">&Ouml;ffnen</div>
                <div class="mediaeditlink" onclick="myMedia.deleteFiles(); return false;">L&ouml;schen</div>
                <div class="clear"></div>
              </div>
              <div class="buttoneditbottom"></div>
              <div class="clear"></div>             
            </div>
          </div>       
          
          <div id="mediaviewtypes">
            <div id="divThumbView" class="iconthumbview" onclick="myMedia.getMediaThumbView(); return false;"></div>
            <div id="divListView" class="iconlistview" onclick="myMedia.getMediaListView(); return false;"></div>            
            <div class="clear"></div>
          </div>
          
          <div id="mediaslider" style="display:none;">
            <div class="slidermediasmall"></div>	          
	          <div id="divMediaSliderTrack" class="slidertrack" style="position:absolute; top:0px; left:14px; width:151px; height: 19px;">
              <div id="divMediaSliderBall" style="width:19px; height:19px;">
                <img src="/zoolu/images/slider/icon_slider_ball.png" width="19" height="19" />
              </div>
            </div>            
            <div class="slidermediabig"></div>
          </div>
          
        </div>
        
        <!-- thumb view -->
        <div id="divThumbViewContainer" class="contentview" style="display:none;">
        </div>
        <!-- list view -->
        <div id="divListViewContainer" class="contentview" style="display:none;">
        </div>
        
        <div class="clear"></div>
      </div> <!-- END divMediaContainer -->      
    </div> <!-- END content -->        

    <!-- overlay transparent-->
    <div id="overlayTrans" class="overlaytrans" style="display:none;"></div>    
    <!-- overlay black 75% -->
    <div id="overlayBlack75" class="overlayblack75" style="display:none;"></div>
    
    <!-- overlay for generated content -->
    <div id="overlayGenContentWrapper" class="overlaycontentwrapper" style="display:none;">
      <table>
        <thead>
          <tr>
            <td class="cornertopleft"></td>
            <td class="topcenter"></td>
            <td class="cornertopright"></td>
          </tr>
          <tr>
            <td class="headerleft"></td>
            <td class="headercenter handle">
              <div class="headerclose" onclick="$('overlayGenContentWrapper').hide(); $('overlayBlack75').hide(); return false;"></div>
              <div class="clear"></div>
            </td>
            <td class="headerright"></td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="contentleft"></td>
            <td class="contentcenter">
              <div id="overlayGenContent" class="overlaycontent">
              </div>
            </td>
            <td class="contentright"></td>
          </tr>
          <tr>
            <td class="cornerbottomleft"></td>
            <td class="bottomcenter"></td>
            <td class="cornerbottomright"></td>
          </tr>
        </tbody>
      </table>
    </div> <!-- END overlay for generated content -->
    
    <!-- overlay SWF Upload -->
    <div id="overlayUpload" class="overlaycontentwrapper" style="display:none;">
      <table>
        <thead>
          <tr>
            <td class="cornertopleft"></td>
            <td class="topcenter"></td>
            <td class="cornertopright"></td>
          </tr>
          <tr>
            <td class="headerleft"></td>
            <td class="headercenter handle">
              <div class="headerclose" onclick="$('overlayUpload').hide(); $('overlayBlack75').hide(); return false;"></div>
              <div class="clear"></div>
            </td>
            <td class="headerright"></td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="contentleft"></td>
            <td class="contentcenter">
              <div class="overlaycontent">
                <div class="oltitle">Medien hochladen</div>
                <div class="spacer1"></div>
                <form id="uploadForm" action="/zoolu/media/upload" method="post" enctype="multipart/form-data">          
				          <div id="divSWFUploadUI"><!-- myMedia.constSWFUploadUI --></div>
				          <noscript style="background-color: #FFFF66; border-top: solid 4px #FF9966; border-bottom: solid 4px #FF9966; margin: 10px 25px; padding: 10px 15px;">
				            We're sorry. SWFUpload could not load. You must have JavaScript enabled to enjoy SWFUpload.
				          </noscript>
				          <div id="divLoadingContent" class="content" style="background-color: #FFFF66; border-top: solid 4px #FF9966; border-bottom: solid 4px #FF9966; margin: 10px 25px; padding: 10px 15px; display: none;">
				            SWFUpload is loading. Please wait a moment...
				          </div>
				          <div id="divLongLoading" class="content" style="background-color: #FFFF66; border-top: solid 4px #FF9966; border-bottom: solid 4px #FF9966; margin: 10px 25px; padding: 10px 15px; display: none;">
				            SWFUpload is taking a long time to load or the load has failed. Please make sure that the Flash Plugin is enabled and that a working version of the Adobe Flash Player is installed.
				          </div>
				          <div id="divAlternateContent" class="content" style="background-color: #FFFF66; border-top: solid 4px #FF9966; border-bottom: solid 4px #FF9966; margin: 10px 25px; padding: 10px 15px; display: none;">
				            We're sorry. SWFUpload could not load. You may need to install or upgrade Flash Player.
				            Visit the <a href="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash">Adobe website</a> to get the Flash Player.
				          </div>
				        </form>
              </div>
            </td>
            <td class="contentright"></td>
          </tr>
          <tr>
            <td class="cornerbottomleft"></td>
            <td class="bottomcenter"></td>
            <td class="cornerbottomright"></td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- END overlay SWF Upload -->
    
    <!-- libaries -->
    <script type="text/javascript" src="/zoolu/js_incs/prototype/element.addons.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- ext.js includes -->
    <script type="text/javascript" src="/zoolu/js_incs/ext.js/ext-build.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- define layout -->
    <script type="text/javascript" src="/zoolu/js_incs/layout.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- core -->
    <script type="text/javascript" src="/zoolu/js_incs/core.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- navigation -->
    <script type="text/javascript" src="/zoolu/js_incs/navigation.js?v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/js_incs/navigation.media.js?v=<?php echo $this->jsVersion; ?>"></script>    
    <!-- media -->
    <script type="text/javascript" src="/zoolu/js_incs/media.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- form -->
    <script type="text/javascript" src="/zoolu/js_incs/form.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- TinyMCE Texteditor -->
    <script type="text/javascript" src="/zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- SWFUpload -->
    <script type="text/javascript" src="/zoolu/js_incs/swfupload/swfupload.js?v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/js_incs/swfupload/plugins/swfupload.swfobject.js?v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/js_incs/swfupload/plugins/swfupload.queue.js?v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/js_incs/swfupload/fileprogress.js?v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/js_incs/swfupload/handlers.js?v=<?php echo $this->jsVersion; ?>"></script>
    
    <script type="text/javascript">//<![CDATA[
      var myCore = new Massiveart.Core();
      var myMedia = new Massiveart.Media();
      var myNavigation = new Massiveart.Navigation.Media();      
      var myForm = new Massiveart.Form();       
      
      var swfu;
      var sessionId = '<?php echo session_id(); ?>';
      
      var currSliderValue = 100;
    
      document.observe('dom:loaded', function() { 
        myNavigation.constRequestChildNav = '/zoolu/media/navigation/childnavigation';        
        myNavigation.topNaviTitle = 'Medien';
        myNavigation.module = <?php echo $this->module; ?>;
        myNavigation.initModuleMEDIA();
        
        var scaleSlider = new Control.Slider('divMediaSliderBall', 'divMediaSliderTrack', 
                                {range: $R(32, 200),
                                 sliderValue: currSliderValue});
        
        scaleSlider.options.onSlide = function(value){
          myMedia.scaleThumbs(value);              
        }
        
        scaleSlider.options.onChange = function(value){
          myMedia.scaleThumbs(value);
        }

        new Draggable('overlayUpload', {handle: 'handle', scroll: window });
        new Draggable('overlayGenContentWrapper', {handle: 'handle', scroll: window });  
      });       
    //]]>
    </script>    
  </body>
</html>