<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
  <head>
    <title>ZOOLU - <?php echo $this->translate->_('products'); ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Language" content="de" />
    <meta name="language" content="de" />

    <link href="/min/g=zExtCss&v=<?php echo $this->jsVersion; ?>" rel="stylesheet" />
    <link href="/min/g=zProductCss&v=<?php echo $this->jsVersion; ?>" rel="stylesheet" />

  </head>
  <body id="myBody">

    <!-- navigation top -->
    <div id="navigation-top">

      <div id="top">

        <div class="toplogo">
          <a href="/zoolu">
            <img src="/zoolu/images/main/logo_zoolu_small.png" width="69" height="17" alt="ZOOLU"/>
          </a>
        </div>
        <div class="topright">
          <div class="faqtitle"><a href="#"><?php echo $this->translate->_('Report_bugs'); ?></a> | <a href="#"><?php echo $this->translate->_('Help_and_FAQ'); ?></a></div>
          <div class="faqicon"><img src="/zoolu/images/icons/icon_help.png" width="16" height="16"/></div>
          <div class="clear"></div>
        </div>

        <div class="clear"></div>
      </div>  <!-- END top -->

      <?php echo $this->layout()->userinfo; ?>

      <div id="navtopleftclient">
        <img id="navtopleftimgclient" width="42" height="40" src="/zoolu/images/zoolu_client_logo.png"/>
      </div>

      <div id="navtopwrapper">
        <?php echo $this->layout()->modules; ?>
        <div id="navtopbreadcrumb" style="display:none;"></div>
      </div>

      <div id="navtopright">
        <img id="navtoprightimg" width="5" height="40" src="/zoolu/images/main/bg_navigation_right.png"/>
      </div>

    </div>
    <!-- END navigation top -->

    <?php echo $this->layout()->navigation; ?>

    <!-- content -->
    <div id="content">

      <!-- content edit -->
      <div id="genFormContainer" class="contentedit" style="display:none;">
      </div>

      <!-- content function widget -->
      <div id="genFormSaveContainer" class="contentfunction" style="display:none;">

      <!-- widget: save, delete, infos, ... -->
      <div class="widgetfunctions">
        <div class="widget224content">
          <div class="widgetcontenttop">

            <!-- alerts for saving, editing, deleting, ... -->
            <div id="divFormSaveLoader" class="alertsave" style="display:none;">
              <div class="alertsaveloader white"><img src="/zoolu/images/main/loader_save.gif" /><a href="#" onclick="myForm.cancleFormSaveLoader(); return false;" style="color:#fff;">Abbrechen</a></div>
            </div>
            <div id="divFormSaveSucces" class="alertsavesucces" style="display:none;">Gespeichert!</div>
            <div id="divFormSaveError" class="alertsaveerror" style="display:none;">Speichern nicht möglich!</div>
            <div id="divFormDeleteSucces" class="alertdeletesucces" style="display:none;">Gel&ouml;scht!</div>

            <!-- save button -->
            <div id="buttonsave" onclick="myForm.save();">
              <div class="button25leftOn"></div>
              <div class="button25centerOn">
                <img class="iconsave" src="/zoolu/images/icons/icon_save_black.png" width="13" height="13"/>
                <div>Speichern</div>
              </div>
              <div class="button25rightOn"></div>
              <div class="clear"></div>
            </div>

            <!-- delete button -->
            <div id="buttondelete" onclick="myForm.deleteElement();" style="display:none;">
              <div class="button25leftOff"></div>
              <div class="button25centerOff">
                <img class="icondelete" src="/zoolu/images/icons/icon_delete_white.png" width="11" height="14"/>
                <div>L&ouml;schen</div>
              </div>
              <div class="button25rightOff"></div>
              <div class="clear"></div>
            </div>

            <div class="clear"></div>
          </div>
          <div class="widgetcontentmain" id="divWidgetMetaInfos">
          </div>

          </div>
        </div>
      </div>
    </div> <!-- END content -->

    <!-- overlay transparent-->
    <div id="overlayTrans" class="overlaytrans" style="display:none;"></div>
    <!-- overlay black 75% -->
    <div id="overlayBlack75" class="overlayblack75" style="display:none;"></div>

    <!-- overlay for generated content -->
    <div id="overlayGenContentWrapper" class="overlaycontentwrapper" style="display:none;">
      <table>
        <thead>
          <tr>
            <td class="cornertopleft"></td>
            <td class="topcenter"></td>
            <td class="cornertopright"></td>
          </tr>
          <tr>
            <td class="headerleft"></td>
            <td class="headercenter handle">
              <div class="headerclose" onclick="$('overlayGenContentWrapper').hide(); $('overlayBlack75').hide(); return false;"></div>
              <div class="clear"></div>
            </td>
            <td class="headerright"></td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="contentleft"></td>
            <td class="contentcenter">
              <div id="overlayGenContent" class="overlaycontent">
              </div>
            </td>
            <td class="contentright"></td>
          </tr>
          <tr>
            <td class="cornerbottomleft"></td>
            <td class="bottomcenter"></td>
            <td class="cornerbottomright"></td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- libaries -->
    <script type="text/javascript" src="/min/g=zJs&v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/min/g=zProductTreeJs&v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js?v=<?php echo $this->jsVersion; ?>"></script>

    <?php echo $this->jsPlugins; ?>
    
    <script type="text/javascript">//<![CDATA[
      var myCore, myNavigation,  myForm,  myProduct, myFolder, myOverlay;

      //document.observe('dom:loaded', function() {
      Event.observe(window, 'load', function() {
        myCore = new Massiveart.Core();
        myNavigation = new Massiveart.Navigation.Products();
        myForm = new Massiveart.Form();
        myProduct = new Massiveart.Product();
        myFolder = new Massiveart.Folder();
        myOverlay = new Massiveart.Overlay();

        myNavigation.constRequestRootNav = '/zoolu/products/navigation/rootnavigation';
        myNavigation.constRequestChildNav = '/zoolu/products/navigation/childnavigation';
        myNavigation.topNaviTitle = '<?php echo $this->translate->_('Products'); ?>';
        myNavigation.rootLevelTypeId = <?php echo $this->rootLevelTypeId; ?>;
        myNavigation.module = <?php echo $this->module; ?>;

        if((typeof(rootLevelId) != 'undefined')){
          myNavigation.setRootLevelId(rootLevelId);
          myNavigation.getRootLevelTreeStart();
        }

        new Draggable('overlayGenContentWrapper', {handle: 'handle', scroll: window });
      });

    //]]>
    </script>
  </body>
</html>