<?php if($this->onlySweepstake) : ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title></title>

  <link type="text/css" rel="stylesheet" href="/website/themes/ivoclarvivadent/css/screen.css" />
  <link type="text/css" rel="stylesheet" href="/website/themes/ivoclarvivadent/sweepstakes/css/sweepstakes.css" />

  <link rel="shortcut icon" href="/website/themes/ivoclarvivadent/favicon.ico" type="image/x-icon"></link>
  
  <script type="text/javascript" src="/min/b=website/themes/ivoclarvivadent&amp;f=js_incs/prototype/prototype.js,js_incs/script.aculous/builder.js,js_incs/script.aculous/effects.js,js_incs/script.aculous/controls.js,js_incs/script.aculous/fader.js,flowplayer/js/flowplayer-3.1.4.min.js,sweepstakes/js_incs/sweepstakes.js"></script>
  
  <script type="text/javascript">//<![CDATA[
    var mySweepstakes;
    document.observe('dom:loaded', function(){
      mySweepstakes = new Sweepstakes();
    });
    //]]>
  </script>
</head>

<body id="body">
<?php endif; ?>
<?php
    include GLOBAL_ROOT_PATH.$this->basePath.$this->file; 
?>
<?php if($this->onlySweepstake) : ?>
  <!-- @start, Google Analytics -->
  <script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  </script>
  <script type="text/javascript">
    try {
      var pageTracker = _gat._getTracker("UA-940616-1");
      pageTracker._setDomainName("www.ivoclarvivadent.com");
      pageTracker._setSessionTimeout("600");
      pageTracker._initData();
      pageTracker._trackPageview();
    } catch(err) {}
  </script>
  <!-- @end, Google Analytics -->

</body>
</html>
<?php endif; ?>