<?php

  require_once (dirname(__FILE__).'/../../helpers/NavigationHelper.php');
  $objHelper = new NavigationHelper();

?>
    <script type="text/javascript">//<![CDATA[
      var folderFormDefaultId = '<?php echo $this->folderFormDefaultId; ?>';
      var productFormDefaultId = '<?php echo $this->productFormDefaultId; ?>';
      var productTemplateDefaultId = '<?php echo $this->productTemplateDefaultId; ?>';
      var productTypeDefaultId = <?php echo $this->productTypeDefaultId; ?>;
    //]]>
    </script>

    <!-- navigation left -->
    <div id="navigation-left">

      <!-- navigation left -->
      <div id="navilefttop2">
        <img width="5" height="5" src="/zoolu/images/main/bg_corner_top_left_white.png"/>
      </div>
      <div id="navirighttop2">
        <img width="5" height="5" src="/zoolu/images/main/bg_corner_top_right_white.png"/>
      </div>
      <div id="divNaviLeft2">
        <div id="divNaviLeftInner">
          <!-- main navigatin -->
          <div id="divNaviLeftMain">
            <?php echo $objHelper->getMainNavigation($this->rootLevels, 'list'); ?>
          </div>
        </div>
      </div>

      <div id="navileftbottom2">
        <img width="5" height="5" src="/zoolu/images/main/bg_corner_bottom_left_white.png"/>
      </div>
      <div id="navirightbottom2">
        <img width="5" height="5" src="/zoolu/images/main/bg_corner_bottom_right_white.png"/>
      </div>
    </div> <!-- END navigation main -->