<?php

  require_once (dirname(__FILE__).'/../../helpers/NavigationHelper.php');
  $objHelper = new NavigationHelper();

?>

            <div id="level<?php echo $this->currLevel; ?>" class="navlevelinner" onmouseover="myNavigation.toggleAddMenuIcon(<?php echo $this->currLevel; ?>,'show');return false;" onmouseout="myNavigation.toggleAddMenuIcon(<?php echo $this->currLevel; ?>,'hide'); return false;">
              <?php echo $objHelper->getNavigationElements($this->rootelements, $this->currLevel); ?>
              <div>&nbsp;</div>
            </div>

            <div id="levelmenu<?php echo $this->currLevel; ?>" class="levelmenu" style="display:none;" onclick="myNavigation.showAddMenu(<?php echo $this->currLevel; ?>); return false;" onmouseover="myNavigation.toggleAddMenuIcon(<?php echo $this->currLevel; ?>,'show');return false;">
              <div><img src="/zoolu/images/icons/icon_add.png" width="16" height="16" alt="<?php echo $this->translate->_('Show_Add_Menu'); ?>"/></div>
            </div>

            <div id="addmenu<?php echo $this->currLevel; ?>" class="addmenu" style="display:none;">
              <div class="addmenutopleft"></div>
              <div class="addmenutopright"></div>
              <div class="clear"></div>
              <div class="addmenucontent">
                <div class="addmenuelement" onclick="myNavigation.addProduct(<?php echo $this->currLevel; ?>); return false;">
                  <img class="icon" src="/zoolu/images/icons/icon_document_new.png" width="16" height="16" alt="<?php echo $this->translate->_('New_Product'); ?>"/>
                  <div class="small white"><?php echo $this->translate->_('New_Product'); ?></div>
                  <div class="clear"></div>
                </div>
                <div class="addmenuelement" onclick="myNavigation.getProductLinkChooser(<?php echo $this->currLevel; ?>); return false;">
                  <img class="icon" src="/zoolu/images/icons/icon_document_new.png" width="16" height="16" alt="<?php echo $this->translate->_('New_Product_Link'); ?>"/>
                  <div class="small white"><?php echo $this->translate->_('New_Product_Link'); ?></div>
                  <div class="clear"></div>
                </div>
                <div class="addmenuelement" onclick="myNavigation.addFolder(<?php echo $this->currLevel; ?>); return false;">
                  <img class="icon" src="/zoolu/images/icons/icon_folder_new.png" width="16" height="16" alt="<?php echo $this->translate->_('New_Folder'); ?>"/>
                  <div class="small white"><?php echo $this->translate->_('New_Folder'); ?></div>
                  <div class="clear"></div>
                </div>
              </div>
            </div>


