<?php
  require_once (dirname(__FILE__).'/../../helpers/ViewHelper.php');
  $objHelper = new ViewHelper();
?>
                 <div class="formsubtitle">Letzte &Auml;nderungen</div>
                 <table class="tablelist">
                   <thead>
                     <tr>
                       <th class="topcornerleft"></th>
                       <th class="topcheckbox"></th>
                       <th class="topicon"></th>
                       <th class="toptitle">Titel</th>
                       <th class="topauthor">Hochgeladen von</th>
                       <th class="topcreated">Hochgeladen am</th>
                       <th class="topcornerright"></th>
                     </tr>
                   </thead>
                   <tbody>
                     <?php echo $objHelper->getDashboardListOutput($this->objFiles);?>
                   </tbody>
                 </table>
                 <div class="listfooter">
                   <div class="listfootercornerleft"></div>
                   <div class="listfootercornerright"></div>
                 </div>
                 <div class="spacer2"></div>