<div class="oltitle"><?php echo $this->overlaytitle; ?></div>
<div class="spacer1"></div>
<div class="field-6 field">
  <input type="text" id="productSearchValue" onkeyup="if(event.keyCode == 13){ myProduct.searchProduct(); return false; }" value=""/>
  <input type="hidden" id="productSearchCurrLevel" value="<?php echo $this->currLevel; ?>"/>
</div>
<div id="productSearchButton" style="float:left; padding-top:2px; cursor:pointer;" onclick="myProduct.searchProduct();">
  <div class="button25leftOn"></div>
  <div class="button25centerOn">
      <div><?php echo $this->translate->_('Search'); ?></div>
  </div>
  <div class="button25rightOn"></div>
  <div class="clear"></div>
</div>
<div style="float: left; padding:6px 0 0 10px;">
  <a href="#" onclick="myProduct.resetProductSearch(); return false;"><?php echo $this->translate->_('Reset'); ?></a>
</div>
<div class="clear"></div>
<div class="olnavigationwrapper" id="productSearchResult"></div>
<div class="spacer1 clear"></div>