<?php

  require_once (dirname(__FILE__).'/../../helpers/ListHelper.php');
  $objHelper = new ListHelper();

?>
        <?php echo $objHelper->getList($this->productPaginator, $this->orderColumn, $this->sortOrder, $this->searchValue); ?>
        <?php echo $this->paginationControl($this->productPaginator, 'Sliding', 'pagination.phtml'); ?>
        <div class="spacer2"></div>
        <script type="text/javascript">//<![CDATA[
          if(typeof(myForm) != 'undefined' && typeof(myCore) != 'undefined'){
            myForm.blnShowFormAlert = <?php echo (($this->blnShowFormAlert == true) ? 'true' : 'false') ?>;
            myCore.deleteAlertMultiMessage = 'Wollen Sie diese %i Produkte l&ouml;schen?';
            myCore.deleteAlertSingleMessage = 'Wollen Sie dieses Produkt l&ouml;schen?';
          }
        //]]>
        </script>