<?php
/**
 * Groups configuration for default Minify implementation
 * @package Minify
 */

/** 
 * You may wish to use the Minify URI Builder app to suggest
 * changes. http://yourdomain/min/builder/
 **/

return array(
  'zCss' => array(
    '//zoolu/css/core_main.css',
    '//zoolu/css/core_navigation.css',
    '//zoolu/css/core_font.css'),
  'zExtCss' => array(
    '//zoolu/js_incs/ext.js/resources/css/ext-all.css',
    '//zoolu/js_incs/ext.js/resources/css/xtheme-gray.css'),
  'zCmsCss' => array(
    '//zoolu/css/core_main.css',
    '//zoolu/css/core_navigation.css',
    '//zoolu/css/core_content.css',
    '//zoolu/css/core_font.css',
    '//zoolu/css/tags.css',
    '//zoolu/css/facebooklist.css'),
  'zCmsJs' => array(
    '//zoolu/js_incs/prototype/prototype.js',
    '//zoolu/js_incs/script.aculous/builder.js',
    '//zoolu/js_incs/script.aculous/effects.js',
    '//zoolu/js_incs/script.aculous/dragdrop.js',
    '//zoolu/js_incs/script.aculous/controls.js',
    '//zoolu/js_incs/script.aculous/slider.js',
    '//zoolu/js_incs/prototype/element.addons.js',
    '//zoolu/js_incs/prototype/facebooklist.js',
    '//zoolu/js_incs/ext.js/ext-build.js',
    '//zoolu/js_incs/core.js',
    '//zoolu/js_incs/layout.js',
    '//zoolu/js_incs/navigation.js',
    '//zoolu/js_incs/navigation.cms.js',
    '//zoolu/js_incs/form.js',
    '//zoolu/js_incs/page.js',
    '//zoolu/js_incs/folder.js',
    '//zoolu/js_incs/overlay.js',
    '//zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js',
    '//zoolu/js_incs/tags.js'),
  'zMediaCss' => array(
    '//zoolu/css/core_main.css',
    '//zoolu/css/core_navigation.css',
    '//zoolu/css/core_content.css',
    '//zoolu/css/core_font.css',
    '//zoolu/css/media.css'),
  'zMediaCmsJs' => array(
    '//zoolu/js_incs/prototype/prototype.js',
    '//zoolu/js_incs/script.aculous/builder.js',
    '//zoolu/js_incs/script.aculous/effects.js',
    '//zoolu/js_incs/script.aculous/dragdrop.js',
    '//zoolu/js_incs/script.aculous/controls.js',
    '//zoolu/js_incs/script.aculous/slider.js',
    '//zoolu/js_incs/prototype/element.addons.js',
    '//zoolu/js_incs/ext.js/ext-build.js',
    '//zoolu/js_incs/core.js',
    '//zoolu/js_incs/layout.js',
    '//zoolu/js_incs/navigation.js',
    '//zoolu/js_incs/navigation.media.js',
    '//zoolu/js_incs/form.js',
    '//zoolu/js_incs/media.js',
    '//zoolu/js_incs/folder.js',
    '//zoolu/js_incs/overlay.js',
    '//zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js',
    '//zoolu/js_incs/swfupload/swfupload.js',
    '//zoolu/js_incs/swfupload/plugins/swfupload.swfobject.js',
    '//zoolu/js_incs/swfupload/plugins/swfupload.queue.js',
    '//zoolu/js_incs/swfupload/fileprogress.js',
    '//zoolu/js_incs/swfupload/handlers.js'),
  'zProductCss' => array(
    '//zoolu/css/core_main.css',
    '//zoolu/css/core_navigation.css',
    '//zoolu/css/core_content.css',
    '//zoolu/css/core_font.css',
    '//zoolu/css/tags.css',
    '//zoolu/css/facebooklist.css'),
  'zProductListJs' => array(
    '//zoolu/js_incs/prototype/prototype.js',
    '//zoolu/js_incs/script.aculous/builder.js',
    '//zoolu/js_incs/script.aculous/effects.js',
    '//zoolu/js_incs/script.aculous/dragdrop.js',
    '//zoolu/js_incs/script.aculous/controls.js',
    '//zoolu/js_incs/script.aculous/slider.js',
    '//zoolu/js_incs/prototype/element.addons.js',
    '//zoolu/js_incs/prototype/facebooklist.js',
    '//zoolu/js_incs/ext.js/ext-build.js',
    '//zoolu/js_incs/core.js',
    '//zoolu/js_incs/layout2.js',
    '//zoolu/js_incs/navigation.js',
    '//zoolu/js_incs/navigation.products.js',
    '//zoolu/js_incs/list.js',
    '//zoolu/js_incs/form.js',
    '//zoolu/js_incs/product.js',
    '//zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js'),
  'zProductTreeJs' => array(
    '//zoolu/js_incs/prototype/prototype.js',
    '//zoolu/js_incs/script.aculous/builder.js',
    '//zoolu/js_incs/script.aculous/effects.js',
    '//zoolu/js_incs/script.aculous/dragdrop.js',
    '//zoolu/js_incs/script.aculous/controls.js',
    '//zoolu/js_incs/script.aculous/slider.js',
    '//zoolu/js_incs/prototype/element.addons.js',
    '//zoolu/js_incs/prototype/facebooklist.js',
    '//zoolu/js_incs/ext.js/ext-build.js',
    '//zoolu/js_incs/core.js',
    '//zoolu/js_incs/layout.js',
    '//zoolu/js_incs/navigation.js',
    '//zoolu/js_incs/navigation.products.js',
    '//zoolu/js_incs/form.js',
    '//zoolu/js_incs/product.js',
    '//zoolu/js_incs/folder.js',
    '//zoolu/js_incs/overlay.js',
    '//zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js',
    '//zoolu/js_incs/tags.js'),
  'zPropertyCss' => array(
    '//zoolu/css/core_main.css',
    '//zoolu/css/core_navigation.css',
    '//zoolu/css/core_content.css',
    '//zoolu/css/core_font.css'),
  'zPropertyJs' => array(
    '//zoolu/js_incs/prototype/prototype.js',
    '//zoolu/js_incs/script.aculous/builder.js',
    '//zoolu/js_incs/script.aculous/effects.js',
    '//zoolu/js_incs/script.aculous/dragdrop.js',
    '//zoolu/js_incs/script.aculous/controls.js',
    '//zoolu/js_incs/script.aculous/slider.js',
    '//zoolu/js_incs/prototype/element.addons.js',
    '//zoolu/js_incs/ext.js/ext-build.js',
    '//zoolu/js_incs/core.js',
    '//zoolu/js_incs/layout.js',
    '//zoolu/js_incs/navigation.js',
    '//zoolu/js_incs/navigation.properties.js',
    '//zoolu/js_incs/form.js',
    '//zoolu/js_incs/form.properties.js',
    '//zoolu/js_incs/overlay.js',
    '//zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js'),
  'zUserCss' => array(
    '//zoolu/css/core_main.css',
    '//zoolu/css/core_navigation.css',
    '//zoolu/css/core_content.css',
    '//zoolu/css/core_font.css',
    '//zoolu/css/tags.css'),
  'zUserJs' => array(
    '//zoolu/js_incs/prototype/prototype.js',
    '//zoolu/js_incs/script.aculous/builder.js',
    '//zoolu/js_incs/script.aculous/effects.js',
    '//zoolu/js_incs/script.aculous/dragdrop.js',
    '//zoolu/js_incs/script.aculous/controls.js',
    '//zoolu/js_incs/script.aculous/slider.js',
    '//zoolu/js_incs/prototype/element.addons.js',
    '//zoolu/js_incs/ext.js/ext-build.js',
    '//zoolu/js_incs/core.js',
    '//zoolu/js_incs/layout2.js',
    '//zoolu/js_incs/navigation.js',
    '//zoolu/js_incs/navigation.users.js',
    '//zoolu/js_incs/list.js',
    '//zoolu/js_incs/form.js',
    '//zoolu/js_incs/form.users.js',
    '//zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js')
);