<?php

  require_once (dirname(__FILE__).'/../../helpers/NavigationHelper.php');
  $objHelper = new NavigationHelper();

?>    
    <script type="text/javascript">//<![CDATA[    
      var folderFormDefaultId = '<?php echo $this->folderFormDefaultId; ?>';
      var fileDefaultDescription = '<?php echo $this->fileDefaultDescription; ?>';
      //myNavigation.rootLevelId = '<?php echo $this->rootLevelId; ?>';
    //]]>
    </script>
    
    <!-- navigation main -->
    <div id="navigation-main">

      <!-- navigation left -->
      <div id="navilefttop">
        <img width="5" height="5" src="/zoolu/images/main/bg_corner_top_left_white.png"/>
      </div>
      <div id="divNaviLeft">
        <div id="divNaviLeftInner">
          <!-- main navigatin -->
          <div id="divNaviLeftMain">
            <?php echo $objHelper->getMediaTypes($this->mediaTypes); ?>
          </div>
        </div>
      </div>
      <div id="navileftbottom">
        <img width="5" height="5" src="/zoolu/images/main/bg_corner_bottom_left_white.png"/>
      </div>

      <!-- navigation center -->
      <div id="divNaviCenter">
        <!-- navigation output container -->
        <div id="divNaviCenterInner">
        </div>
      </div>

      <!-- navigation right -->
      <div id="navirighttop">
        <img width="5" height="5" src="/zoolu/images/main/bg_corner_top_right_white.png"/>
      </div>
      <div id="divNaviRight">
        <div id="divNaviRightInner">
        </div>
      </div>
      <div id="navirightbottom">
        <img width="5" height="5" src="/zoolu/images/main/bg_corner_bottom_right_white.png"/>
      </div>

      <div class="clear"></div>
    </div> <!-- END navigation main -->