<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
  <head>
    <title>ZOOLU</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Language" content="de" />
    <meta name="language" content="de" />

    <link href="/min/g=zExtCss&v=<?php echo $this->jsVersion; ?>" rel="stylesheet" />
    <link href="/min/g=zCss&v=<?php echo $this->jsVersion; ?>" rel="stylesheet" />

  </head>
  <body id="myBody">

    <!-- navigation top -->
    <div id="navigation-top">

      <div id="top">

        <div class="toplogo">
          <a href="/zoolu">
            <img src="/zoolu/images/main/logo_zoolu_small.png" width="69" height="17" alt="ZOOLU"/>
          </a>
        </div>
        <div class="topright">
          <div class="faqtitle"><a href="http://code.google.com/p/zoolu/issues/list" target="_blank"><?php echo $this->translate->_('Report_bugs'); ?></a> | <a href="#"><?php echo $this->translate->_('Help_and_FAQ'); ?></a></div>
          <div class="faqicon"><img src="/zoolu/images/icons/icon_help.png" width="16" height="16"/></div>
          <div class="clear"></div>
        </div>

        <div class="clear"></div>
      </div>  <!-- END top -->

      <?php echo $this->layout()->userinfo; ?>

      <!--
      <div id="navtopleft">
        <img id="navtopleftimg" width="5" height="40" src="/zoolu/images/main/bg_navigation_left.png"/>
      </div>
       -->

      <div id="navtopleftclient">
        <img id="navtopleftimgclient" width="42" height="40" src="/zoolu/images/zoolu_client_logo.png"/>
      </div>

      <div id="navtopwrapper">
        <?php echo $this->layout()->modules; ?>
        <div id="navtopbreadcrumb" style="display:none;"></div>
      </div>

      <div id="navtopright">
        <img id="navtoprightimg" width="5" height="40" src="/zoolu/images/main/bg_navigation_right.png"/>
      </div>

    </div>
    <!-- END navigation top -->

  </body>
</html>