<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
  <head>
    <title>ZOOLU - CMS</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Language" content="de" />
    <meta name="language" content="de" />

    <!-- ext.js css -->
    <link rel="stylesheet" type="text/css" href="/zoolu/js_incs/ext.js/resources/css/ext-all.css?v=<?php echo $this->cssVersion; ?>" />
    <link rel="stylesheet" type="text/css" href="/zoolu/js_incs/ext.js/resources/css/xtheme-gray.css?v=<?php echo $this->cssVersion; ?>" />

    <!-- css -->
    <link href="/zoolu/css/core_main.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />
    <link href="/zoolu/css/core_navigation.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />
    <link href="/zoolu/css/core_content.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />
    <link href="/zoolu/css/core_font.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />
    <link href="/zoolu/css/tags.css?v=<?php echo $this->cssVersion; ?>" rel="stylesheet" />

    <!-- libaries -->
    <script type="text/javascript" src="/zoolu/js_incs/prototype/prototype.js?v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/js_incs/script.aculous/scriptaculous.js?v=<?php echo $this->jsVersion; ?>"></script>

  </head>
  <body id="myBody">

    <!-- navigation top -->
    <div id="navigation-top">

      <div id="top">

        <div class="toplogo">
          <a href="/zoolu">
            <img src="/zoolu/images/main/logo_zoolu_small.png" width="69" height="17" alt="ZOOLU"/>
          </a>
        </div>
        <div class="topright">
          <div class="faqtitle"><a href="#"><?php echo $this->translate->_('Report_bugs'); ?></a> | <a href="#"><?php echo $this->translate->_('Help_and_FAQ'); ?></a></div>
          <div class="faqicon"><img src="/zoolu/images/icons/icon_help.png" width="16" height="16"/></div>
          <div class="clear"></div>
        </div>

        <div class="clear"></div>
      </div>  <!-- END top -->

      <?php echo $this->layout()->userinfo; ?>

      <div id="navtopleftclient">
        <img id="navtopleftimgclient" width="42" height="40" src="/zoolu/images/zoolu_client_logo.png"/>
      </div>

      <div id="navtopwrapper">
        <div id="navtopinner">
          <div class="navtop">
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_left.png"/></div>
            <div class="navtoplink" onmouseover="this.style.cursor='pointer';" onclick="location.href='/zoolu/cms'"><?php echo strtoupper($this->translate->_('Portals')); ?></div>
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_right.png"/></div>
          </div>
          <div class="navtop">
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_left.png"/></div>
            <div class="navtoplink" onmouseover="this.style.cursor='pointer';" onclick="location.href='/zoolu/media'"><?php echo strtoupper($this->translate->_('Media')); ?></div>
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_right.png"/></div>
          </div>
          <div class="navtopinnerright">
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_left.png"/></div>
            <div class="navtoplink" onmouseover="this.style.cursor='pointer';" onclick="location.href='/zoolu/properties'"><?php echo $this->translate->_('Settings'); ?></div>
            <div class="navtopcorner"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_right.png"/></div>
          </div>
          <div class="navtopinnerright">
            <div class="navtopcorner_on"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_left.png"/></div>
            <div class="navtoplink_on" onmouseover="this.style.cursor='pointer';" onclick="location.href='/zoolu/users'"><?php echo $this->translate->_('User_administration'); ?></div>
            <div class="navtopcorner_on"><img width="5" height="30" src="/zoolu/images/main/bg_navelement_right.png"/></div>
          </div>
          <div class="clear"></div>
        </div>
        <div id="navtopbreadcrumb" style="display:none;"></div>
      </div>

      <div id="navtopright">
        <img id="navtoprightimg" width="5" height="40" src="/zoolu/images/main/bg_navigation_right.png"/>
      </div>

    </div>
    <!-- END navigation top -->

    <?php echo $this->layout()->navigation; ?>

    <!-- content -->
    <div id="content2">

      <!-- widget: save, delete, infos, ... -->
      <div class="widgetfunctions">
        <div class="widgetcontenttop">
          <div id="widgetcontentlefttop">
		        <img width="5" height="5" src="/zoolu/images/main/bg_corner_top_left_white.png"/>
		      </div>
          <div id="widgetcontentrighttop">
            <img width="5" height="5" src="/zoolu/images/main/bg_corner_top_right_white.png"/>
          </div>

          <!-- alerts for saving, editing, deleting, ... -->
          <div id="divFormSaveLoader" class="alertsave" style="display:none;">
            <div class="alertsaveloader white"><img src="/zoolu/images/main/loader_save_gray.gif" /><a href="#" onclick="myForm.cancleFormSaveLoader(); return false;" style="color:#fff;">Abbrechen</a></div>
          </div>
          <div id="divFormSaveSucces" class="alertsavesucces" style="display:none;">Gespeichert!</div>
          <div id="divFormSaveError" class="alertsaveerror" style="display:none;">Speichern nicht möglich!</div>
          <div id="divFormDeleteSucces" class="alertdeletesucces" style="display:none;">Gel&ouml;scht!</div>

          <div id="genListFunctions" style="display:none;">
            <!-- new button -->
            <div id="buttonsave" onclick="myNavigation.getAddForm();">
              <div class="button25leftOn"></div>
              <div class="button25centerOn">
                <img class="iconsave" src="/zoolu/images/icons/icon_save_black.png" width="13" height="13"/>
                <div>Neu</div>
              </div>
              <div class="button25rightOn"></div>
              <div class="clear"></div>
            </div>

            <!-- edit menu -->
            <div id="buttonedit" onclick="return false;">
              <div class="buttonedittop"></div>
              <div id="buttonmediaedittitle" class="buttoneditmiddle white" onclick="myList.toggleEditMenu(this.id); return false;">Bearbeiten</div>
              <div class="buttoneditbottom"></div>
              <div class="clear"></div>
            </div>

            <div id="buttonEditMenu" class="buttoneditmenu"  style="display:none;">
              <div class="buttoneditmenuinner">
                <div class="buttoneditlink" onclick="myList.del(); return false;">L&ouml;schen</div>
                <div class="clear"></div>
              </div>
              <div class="buttoneditbottom"></div>
              <div class="clear"></div>
            </div>
          </div>

          <div id="genFormFunctions" style="display:none;">
            <!-- save button -->
            <div id="buttonsave" onclick="myForm.save();">
              <div class="button25leftOn"></div>
              <div class="button25centerOn">
                <img class="iconsave" src="/zoolu/images/icons/icon_save_black.png" width="13" height="13"/>
                <div>Speichern</div>
              </div>
              <div class="button25rightOn"></div>
              <div class="clear"></div>
            </div>

            <!-- delete button -->
            <div id="buttondelete" onclick="myForm.deleteElement();">
              <div class="button25leftOff"></div>
              <div class="button25centerOff">
                <img class="icondelete" src="/zoolu/images/icons/icon_delete_white.png" width="11" height="14"/>
                <div>L&ouml;schen</div>
              </div>
              <div class="button25rightOff"></div>
              <div class="clear"></div>
            </div>
          </div>

          <div class="clear"></div>
        </div>
      </div>

      <div id="genFormContainer" class="contentedit2" style="display:none;"></div>

      <div id="genListContainer" class="contentedit2" style="display:none;"></div>
    </div>

    <!-- libaries -->
    <script type="text/javascript" src="/zoolu/js_incs/prototype/element.addons.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- ext.js includes -->
    <script type="text/javascript" src="/zoolu/js_incs/ext.js/ext-build.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- core -->
    <script type="text/javascript" src="/zoolu/js_incs/core.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- define layout -->
    <script type="text/javascript" src="/zoolu/js_incs/layout2.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- navigation -->
    <script type="text/javascript" src="/zoolu/js_incs/navigation.js?v=<?php echo $this->jsVersion; ?>"></script>
    <script type="text/javascript" src="/zoolu/js_incs/navigation.users.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- list -->
    <script type="text/javascript" src="/zoolu/js_incs/list.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- users -->
    <script type="text/javascript" src="/zoolu/js_incs/users.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- form -->
    <script type="text/javascript" src="/zoolu/js_incs/form.js?v=<?php echo $this->jsVersion; ?>"></script>
    <!-- TinyMCE Texteditor -->
    <script type="text/javascript" src="/zoolu/tinymce/jscripts/tiny_mce/tiny_mce.js?v=<?php echo $this->jsVersion; ?>"></script>

    <script type="text/javascript">//<![CDATA[
      var myCore = new Massiveart.Core();
      var myNavigation = new Massiveart.Navigation.Users();
      var myList = new Massiveart.List();
      var myForm = new Massiveart.Form();

      document.observe('dom:loaded', function() {
        myNavigation.constRequestChildNav = '/zoolu/media/navigation/childnavigation';
        myNavigation.topNaviTitle = '<?php echo $this->translate->_('User_administration'); ?>';
        myNavigation.module = <?php echo $this->module; ?>;
      });
    //]]>
    </script>
  </body>
</html>