<?php

  require_once (dirname(__FILE__).'/../../helpers/ListHelper.php');
  $objHelper = new ListHelper();

?>
        <?php echo $objHelper->getList($this->userPaginator, $this->orderColumn, $this->sortOrder, $this->searchValue); ?>
        <?php echo $this->paginationControl($this->userPaginator, 'Sliding', 'pagination.phtml'); ?>
        <div class="spacer2"></div>
        <script type="text/javascript">//<![CDATA[
          myForm.blnShowFormAlert = <?php echo (($this->blnShowFormAlert == true) ? 'true' : 'false') ?>;
          myCore.deleteAlertMultiMessage = 'Wollen Sie diese %i Benutzer l&ouml;schen?';
          myCore.deleteAlertSingleMessage = 'Wollen Sie diesen Benutzer l&ouml;schen?';         
        //]]>
        </script>