      <div id="userwrapper">
        <div class="usercorner">
          <img width="240" height="4" src="/zoolu/images/main/bg_smallsidebox_top.png"/>
        </div>
        <div id="usercontent">
          <div id="usercontenticon">
            <img width="25" height="25" src="/zoolu/images/main/user_default.jpg"/>
          </div>
          <div id="usercontentuser">
            <div class="headerusername"><?php echo htmlentities($this->user->fname.' '.$this->user->sname, ENT_COMPAT, Zend_Registry::get('Core')->sysConfig->encoding->default, false); ?></div>
            <div class="headerdepartement"><a href="#"><?php echo $this->translate->_('My_Settings'); ?>,</a> <a href="/zoolu/users/user/logout"><?php echo $this->translate->_('Logout'); ?></a></div>
          </div>
          <div class="clear"></div>
        </div>
        <div class="usercorner">
          <img width="240" height="4" src="/zoolu/images/main/bg_smallsidebox_bottom.png"/>
        </div>
        <div class="clear"></div>
      </div>