        <?php if($this->languageOptions != '') : ?>
        <div class="pagelanguagecontainer">
          <select id="selectLanguageId" onchange="myForm.changeLanguage(this.value); return false;">
            <?php echo $this->languageOptions; ?>
          </select>
        </div>
        <?php endif; ?>
        <div class="formtitle"><?php echo $this->formtitle; ?></div>
        <?php echo $this->form; ?>
				<div class="clear"></div>
				<div style="display:none;" id="divMetaInfos">
				  <table cellpadding="0" cellspacing="0">
	          <?php if($this->module == $this->core->sysConfig->modules->cms) : ?>
	            <tr>
	              <td class="tdImportant">Status:</td>
	              <td>
	                <select id="statusSelect" class="important" onchange="$('idStatus').setValue(this.value); return false;">
	                  <?php echo $this->statusOptions; ?>
	                </select>
	              </td>
	            </tr>
	            <?php if($this->publishDate != '') : ?>
	            <tr>
	              <td class="tdNormal">Ver&ouml;ffentlicht:</td>
	              <td>
	                <div class="publishdate"><?php echo $this->publishDate; ?></div>
	                <!-- <img class="iconcalendar" src="/zoolu/images/icons/icon_calendar_purple.png" width="13" height="15"/> -->
	                <div class="clear"></div>
	              </td>
	            </tr>
	            <?php endif; ?>
	            <!--
	            <tr>
	              <td class="tdNormal">Sicherheit:</td>
	              <td>
	                <select class="normal">
	                  <option value="1">&Ouml;ffentlich</option>
	                  <option value="2">Privat</option>
	                </select>
	              </td>
	            </tr>
	            -->
	            <tr>
	              <td class="tdNormal">Author:</td>
	              <td>
	                <select id="creatorSelect" class="normal" onchange="$('creator').setValue(this.value); return false;">
	                  <?php echo $this->creatorOptions; ?>
	                </select>
	              </td>
	            </tr>
	            <tr>
	              <td class="tdNormal"><input type="checkbox" name="showinnavigation" id="showinnavigation"<?php ($this->showinnavigation == 1) ? print(' checked="checked"') : print(''); ?> onclick="$('showInNavigation').value = this.checked ? '1' : '0'"/></td>
	              <td><label for="showinnavigation">in Navigation anzeigen</label></td>
	            </tr>
	            <tr>
	              <td class="tdNormal"><input type="checkbox" name="urlfolder" id="urlfolder"<?php ($this->isurlfolder == 1) ? print(' checked="checked"') : print(''); ?> onclick="$('isUrlFolder').value = this.checked ? '1' : '0'"/></td>
	              <td><label for="urlfolder">in URL-Pfad &uuml;bernehmen</label></td>
	            </tr>
	            <?php if($this->version > 0) : ?>
	            <!--<tr>
	              <td class="tdNormal">Version:</td>
	              <td>
	                <div class="currversion"><?php echo $this->version; ?>.0</div>
	                 <div id="buttonnewversion">
	                  <div class="button17leftOff"></div>
	                  <div class="button17centerOff">
	                    <img src="/zoolu/images/icons/icon_plus_white_small.png" width="8" height="8"/>
	                    <div>Neue Version</div>
	                  </div>
	                  <div class="button17rightOff"></div>
	                </div>
	                <div class="clear"></div>
	              </td>
	            </tr>-->
	            <?php endif; ?>
            <?php endif; ?>
            <?php if($this->changeUser != '' && $this->changeDate != '') : ?>
            <tr>
              <td class="tdNormal">Letzte &Auml;nderung:</td>
              <td><?php echo $this->changeDate; ?><br/><?php echo $this->changeUser; ?></td>
            </tr>
            <?php endif; ?>
            <?php if($this->version > 1 && $this->module == $this->core->sysConfig->modules->cms) : ?>
            <!-- <tr>
              <td class="tdNormal">&nbsp;</td>
              <td><a href="#">Versionsliste</a></td>
            </tr> -->
            <?php endif; ?>
          </table>
				</div>
				<script type="text/javascript">//<![CDATA[
          myForm.blnShowFormAlert = <?php echo (($this->blnShowFormAlert == true) ? 'true' : 'false') ?>;
          myForm.selectNavigationItemNow = <?php echo (($this->selectNavigationItemNow && $this->selectNavigationItemNow == true) ? 'true' : 'false') ?>;
          <?php if($this->itemId): ?>myNavigation.itemId = '<?php echo $this->itemId ?>';<?php endif; ?>
        //]]>
        </script>